USE [master]
GO

/****** Object:  Database [university]    Script Date: 5/26/2026 10:58:02 AM ******/
CREATE DATABASE [university]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'university', FILENAME = N'C:\Users\s.sardarizadeh\university.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'university_log', FILENAME = N'C:\Users\s.sardarizadeh\university_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [university].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [university] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [university] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [university] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [university] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [university] SET ARITHABORT OFF 
GO

ALTER DATABASE [university] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [university] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [university] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [university] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [university] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [university] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [university] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [university] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [university] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [university] SET  ENABLE_BROKER 
GO

ALTER DATABASE [university] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [university] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [university] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [university] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [university] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [university] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [university] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [university] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [university] SET  MULTI_USER 
GO

ALTER DATABASE [university] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [university] SET DB_CHAINING OFF 
GO

ALTER DATABASE [university] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [university] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [university] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [university] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [university] SET QUERY_STORE = ON
GO

ALTER DATABASE [university] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [university] SET  READ_WRITE 
GO


